### ISSUE TITLE
Disabling Bounds Checking For Faster Decode/Encode

### ISSUE THREAD

**Issue by mmstick** [sourrust/flac#6]
I notice that you are performing a lot of indexing throughout the application, but if you were to disable bounds checking for indexing you could gain a very large performance improvement. In example, you could take this section of code:

``` rust
pub fn decode_left_side<S: Sample>(buffer: &mut [S]) {
  let block_size = buffer.len() / 2;

  for i in 0..block_size {
    let left = buffer[i];
    let side = buffer[i + block_size];

    // right channel
    buffer[i + block_size] = left - side;
  }
}
```

Then rewrite it with this using `get_unchecked()` to bypass the bounds checking and gain a sizeable performance improvements.

``` rust
pub fn decode_left_side<S: Sample>(buffer: &mut [S]) {
  let block_size = buffer.len() / 2;

  for i in 0..block_size {
    buffer[i + block_size] = unsafe {
      let left = buffer.get_unchecked(i);
      let side = buffer.get_unchecked(i + block_size);
      left - side
    }
  }
}
```

**Comment by sourrust** [comment]
Thanks for the advice. I'll look more into the actually performance improvements later in the week, but I just put it into master. I'm going to look for more instances where I change to unchecked bounds.

I've been meaning to look more into the Rustonomicon book to explore the unsafe parts of Rust and there is more of a reason to now.
